site_name: NexthinkPSUtils
repo_url: https://github.com/joshwright10/NexthinkPSUtils
site_author: Josh Wright
edit_uri: edit/master/docs/
theme: readthedocs
copyright: "NexthinkPSUtils is licensed under the <a href='https://raw.githubusercontent.com/joshwright10/NexthinkPSUtils/master/LICENSE'>MIT license"
pages:
  - Home: index.md
  - Configuration: gettingsetup.md
  - Nexthink:
      - Exporting Dashboard Modules: exportingdashboardmodules.md
  - Scenarios:
      - Remote Action Dependencies: scenarios/dependenciesremoteaction.md
      - Category Dependencies: scenarios/dependenciescategory.md
      - Metric Dependencies: scenarios/dependenciesmetric.md
      - Score Dependencies: scenarios/dependenciesscore.md
      - Campaign Dependencies: scenarios/dependenciescampaign.md
  - Release Notes: RELEASE.md
  - Functions:
      - Get-NxtCampaignUsageInMetrics: functions/Get-NxtCampaignUsageInMetrics.md
      - Get-NxtCampaignUsageInRemoteActions: functions/Get-NxtCampaignUsageInRemoteActions.md
      - Get-NxtCampaignUsageInScores: functions/Get-NxtCampaignUsageInScores.md
      - Get-NxtCategoryUsageInCampaigns: functions/Get-NxtCategoryUsageInCampaigns.md
      - Get-NxtCategoryUsageInMetrics: functions/Get-NxtCategoryUsageInMetrics.md
      - Get-NxtCategoryUsageInScores: functions/Get-NxtCategoryUsageInScores.md
      - Get-NxtMetricUsageInDashboards: functions/Get-NxtMetricUsageInDashboards.md
      - Get-NxtRemoteActionSummary: functions/Get-NxtRemoteActionSummary.md
      - Get-NxtRemoteActionUsageInMetrics: functions/Get-NxtRemoteActionUsageInMetrics.md
      - Get-NxtRemoteActionUsageInRemoteActions: functions/Get-NxtRemoteActionUsageInRemoteActions.md
      - Get-NxtRemoteActionUsageInScores: functions/Get-NxtRemoteActionUsageInScores.md
      - Get-NxtScoreUsageInMetrics: functions/Get-NxtScoreUsageInMetrics.md
      - Get-NxtScoreUsageInScores: functions/Get-NxtScoreUsageInScores.md
      - Get-NxtUnusedMetrics: functions/Get-NxtUnusedMetrics.md

